name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      # Code Quality
      - run: npm run lint:ci
      - run: npm run lint:styles
      - run: npm test

      # App build and deployment
      - name: Next.js build & static export
        run: npm run build && npm run export
        env:
          BASE_PATH: /insights-training-app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with:
          branch: staging # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
          clean: true
